language: ruby

services:
  - postgresql

before_script:
  - psql -U postgres -c 'CREATE DATABASE chitter_test;'
  - psql -U postgres -d chitter_test -f db/migrations/01_create_peeps_table.sql
  - psql -U postgres -d chitter_test -f db/migrations/02_update_with_date.sql
  - psql -U postgres -d chitter_test -f db/migrations/03_create_users_table.sql
  - psql -U postgres -d chitter_test -f db/migrations/04-update_peeps_wit_peep_name.sql
  
script:
  - bundle exec rspec
